---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: asr-service
    k8s.kuboard.cn/name: asr-service
  name: asr-service
  namespace: default
  resourceVersion: '464156206'
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: asr-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-07-02T19:42:00+08:00'
      creationTimestamp: null
      labels:
        app: asr-service
    spec:
      containers:
        - env:
            - name: WORKERS
              value: '10'
            - name: BATCH
              value: '12'
            - name: BATCH_TIMEOUT
              value: '10'
            - name: LOG_LEVEL
              value: INFO
            - name: MAX_CONCURRENT_REQUESTS
              value: '2048'
            - name: MODEL_PRECISION
              value: trt_fp16
            - name: VAD_SESSION_POOL_SIZE
              value: '2'
            - name: GPU_STREAM_POOL_SIZE
              value: '4'
            - name: CPU_THREAD_POOL_SIZE
              value: '32'
            - name: ENABLE_WORD_TIMESTAMP
              value: 'true'
            - name: ENABLE_SENTENCE_TIMESTAMP
              value: 'true'
            - name: PUNC_MAX_LEN
              value: '200'
            - name: PUNC_INTRA_OP_THREADS
              value: '1'
            - name: ENABLE_HOTWORD
              value: 'true'
            - name: NFILTER
              value: '50'
            - name: ENABLE_FAISS_CORRECTION
              value: 'true'
            - name: FAISS_TOPK
              value: '30'
            - name: FAISS_PINYIN_WEIGHT
              value: '0.75'
            - name: FAISS_EDIT_WEIGHT
              value: '0.25'
            - name: FAISS_SCORE_THRESHOLD
              value: '0.85'
            - name: GAP_THRESHOLD
              value: '0.05'
            - name: FINAL_SCORE_THRESHOLD
              value: '0.88'
            - name: OMP_NUM_THREADS
              value: '1'
            - name: MKL_NUM_THREADS
              value: '1'
            - name: OPENBLAS_NUM_THREADS
              value: '1'
            - name: VERBOSE
              value: '0'
          image: 'zhxgharbor.istarshine.com/asr/asr_infer_master:v1-20260713'
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: asr-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: '40'
              memory: 64Gi
              nvidia.com/gpu: '1'
            requests:
              cpu: '32'
              memory: 48Gi
              nvidia.com/gpu: '1'
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        asr: asr-gpu
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: asr-service
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
status:
  availableReplicas: 6
  conditions:
    - lastTransitionTime: '2026-07-02T13:31:50Z'
      lastUpdateTime: '2026-07-13T06:18:39Z'
      message: ReplicaSet "asr-service-6c875c4594" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2026-07-13T06:26:15Z'
      lastUpdateTime: '2026-07-13T06:26:15Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 91
  readyReplicas: 6
  replicas: 6
  updatedReplicas: 6

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: asr-service
  name: asr-service
  namespace: default
  resourceVersion: '464156767'
spec:
  clusterIP: 10.109.205.134
  clusterIPs:
    - 10.109.205.134
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      nodePort: 30960
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: asr-service
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}